### ISSUE TITLE
Upgrading from v0.12/lower to v0.13 breaks existing media

### ISSUE THREAD

**Issue by tomjn** [humanmade/asset-manager-framework#55]
Despite making changes to support the new API, v0.13 uses a post meta value to store the source URL. This meta is not present in assets used in 0.12, resulting in broken images on sites that upgrade to the new version.

This means either a migration is required to use 0.13, or a fallback needs to be implemented, but neither are mentioned in the release notes.

Issue tracked down to changes in https://github.com/humanmade/asset-manager-framework/pull/35

**Comment by tomjn** [comment]
This function is the likely culprit for the compatibility break:

```php
function replace_attachment_url( $url, int $attachment_id ) : string {
	$attachment = get_post( $attachment_id );
	if ( ! is_amf_asset( $attachment ) ) {
		return $url ?: '';
	}

	return wp_unslash( get_post_meta( $attachment_id, '_amf_source_url', true ) ?: '' );
}
```

If `_amf_source_url` is missing or unset, the resulting URL will be a falsey value for all AMF assets prior to the upgrade.

https://github.com/humanmade/asset-manager-framework/blob/master/inc/namespace.php#L225-L232

I'm considering 2 options:

 - separate the `get_post_meta` out and check if it has a valid value, if so return that, else return `$url`
 - instead of returning `$url`, attempt to backfill the data

**Comment by svandragt** [comment]
This is specifically about `_amf_source_url` which got introduced in https://github.com/humanmade/asset-manager-framework/commit/889c6d7859be01e57d976280ea27eb33bad92f71 and is retrieved without fallback for existing images.

**Comment by roborourke** [comment]
Surprised this has only come up now tbh, I'm not sure what the ideal fallback value is without looking at legacy data.

Your issue doesn't describe exactly _how_ images are broken, do you have examples that might help to determine the proper mitigation?

Of your 2 options I'd probably try this one:

> separate the get_post_meta out and check if it has a valid value, if so return that, else return $url

e.g 

```
return wp_unslash( get_post_meta( $attachment_id, '_amf_source_url', true ) ?: $url );
```

There might be other unintended consequences to that though.

**Comment by lebz** [comment]
I might not have the best way to explain the problem technically. but i can explain what happens currently and maybe the history on how we use the plugin on SiemensWorld. 

On SiemensWorld we are not allowed to upload images to the site from the desktop. 

Previously (we were running version 0.8.1) - we didnt have the option to choose from either Local Media / Siemens Digital Assets Management. Siemens Digital Assets Management folder(option) was the default

When you open a post created before the upgrade(plugin upgrade ) in post edit mode, the featured images is blanks
<img width="1415" alt="Screenshot 2022-08-15 at 10 46 14" src="https://user-images.githubusercontent.com/6667094/185345058-c31cfd38-345e-4f89-9f08-aa468389003a.png">

When you click on the blank space to replace the image you get this. All the meta data related to the asset are returned but the `file path`
<img width="1372" alt="Screenshot 2022-08-16 at 12 28 09" src="https://user-images.githubusercontent.com/6667094/185353422-52d4aa4b-3430-4d0b-98b6-8abcfc92ffe2.png">


Then on the home page the featured images are not visible at all.

On single post view i get a PHP NOTICE `Undefined index: url ` on line `368` of file` asset-manager-framework/inc/namespace.php`

With the new version when you save a featured image, it creates this entry in the [DB]
<img width="1081" alt="Screenshot 2022-08-18 at 10 09 10" src="https://user-images.githubusercontent.com/6667094/185344278-3fb9766d-af00-4854-8c19-579354c220cc.png">

i assume its because of 
`add_post_meta( $attachment_id, '_amf_source_url', wp_slash( $selection['url'] ), true );
add_post_meta( $attachment_id, '_amf_provider', wp_slash( $provider->get_id() ), true );`

All featured images created after the upgrade work as they should, i assume because of checking for `_amf_source_url` and `_amf_provider`

On single post view images blocks work fine and i dont get any PHP notice messages.

What i tried was  to add `$url = $attachment->guid; `to `fix_media_url` and update this function
```
function replace_attachment_url_override( $url, int $attachment_id ) : string {
	$attachment = get_post( $attachment_id );
	if ( ! is_amf_asset( $attachment ) && empty( $url )) {
		return $url ?: '';
	}

	return wp_unslash( get_post_meta( $attachment_id, '_amf_source_url', true ) ?: $url );
}
```

that fixed the blank featured images, when editing posts. Im still stuck on making sure the show on the home page and making sure i dont get the  PHP notice. I did the changes on our theme functions.php file.


I hope the context helps in answering any open questions.

**Comment by tomjn** [comment]
I've integrated a version of the `replace_attachment_url_override` override into the plugin in #57, along with a potential fix in another location that uses the same meta. It's untested at the moment, and a small chance exists I introduced an infinite loop. Will circle back to this on Friday

**Comment by tomjn** [comment]
Noting that updates were made to the PR to fix the loop and a PHP notice resolved, it's ready for code review cc @roborourke @svandragt

**Comment by svandragt** [comment]
Left review
